# Generated by Django 5.1.1 on 2025-05-27 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BasepackProcessStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.IntegerField(default=0)),
                ("process", models.TextField(max_length=30, unique=True)),
                ("time", models.FloatField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Beat",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField(max_length=40)),
                ("salesman_id", models.IntegerField()),
                ("salesman_code", models.CharField(max_length=30)),
                ("salesman_name", models.TextField(max_length=40)),
                ("days", models.TextField(max_length=40)),
                ("plg", models.TextField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Billing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("status", models.IntegerField()),
                ("error", models.TextField(blank=True, max_length=100000, null=True)),
                (
                    "start_bill_no",
                    models.TextField(blank=True, max_length=10, null=True),
                ),
                ("end_bill_no", models.TextField(blank=True, max_length=10, null=True)),
                ("bill_count", models.IntegerField(blank=True, default=0, null=True)),
                ("date", models.DateField()),
                ("automatic", models.BooleanField(db_default=False, default=False)),
            ],
        ),
        migrations.CreateModel(
            name="BillStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.TextField(max_length=30)),
                ("count", models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="ChequeDeposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank",
                    models.CharField(
                        choices=[
                            ("KVB 650", "KVB 650"),
                            ("SBI", "SBI"),
                            ("CANARA", "CANARA"),
                            ("BARODA", "BARODA"),
                            ("UNION BANK", "UNION BANK"),
                            ("AXIS", "AXIS"),
                            ("HDFC", "HDFC"),
                            ("CENTRAL BANK", "CENTRAL BANK"),
                            ("INDIAN BANK", "INDIAN BANK"),
                            ("IOB", "IOB"),
                            ("ICICI", "ICICI"),
                            ("CUB", "CUB"),
                            ("KOTAK", "KOTAK"),
                            ("SYNDICATE", "SYNDICATE"),
                            ("TMB", "TMB"),
                            ("UNITED BANK", "UNITED BANK"),
                            ("TCB", "TCB"),
                            ("PGB", "PGB"),
                        ],
                        max_length=100,
                    ),
                ),
                ("cheque_no", models.CharField(max_length=20)),
                ("amt", models.FloatField()),
                ("cheque_date", models.DateField()),
                ("deposit_date", models.DateField(blank=True, null=True)),
                ("entry_date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("master_code", models.CharField(blank=True, max_length=10, null=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("type", models.CharField(db_default="shop", max_length=10)),
                ("addr", models.CharField(blank=True, max_length=150, null=True)),
                ("pincode", models.IntegerField(blank=True, null=True)),
                ("ctin", models.CharField(blank=True, max_length=20, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("hul_code", models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                "verbose_name_plural": "Party",
            },
        ),
        migrations.CreateModel(
            name="PendingSheet",
            fields=[
                (
                    "sheet_no",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("salesman", models.TextField(max_length=30)),
                ("beat", models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="SalesmanLoadingSheet",
            fields=[
                (
                    "inum",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("salesman", models.TextField(max_length=30)),
                ("party", models.TextField(blank=True, max_length=30, null=True)),
                ("beat", models.TextField(max_length=30)),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "key",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("status", models.BooleanField(default=True)),
                ("value", models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sync",
            fields=[
                (
                    "process",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "name",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("vehicle_no", models.CharField(max_length=30)),
                ("name_on_impact", models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BillingProcessStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.IntegerField(default=0)),
                ("process", models.TextField(max_length=30)),
                ("time", models.FloatField(blank=True, null=True)),
                (
                    "billing",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_status",
                        to="app.billing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankStatement",
            fields=[
                ("date", models.DateField()),
                ("idx", models.IntegerField()),
                (
                    "id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("ref", models.TextField(max_length=200)),
                ("desc", models.TextField(max_length=200)),
                ("amt", models.IntegerField()),
                (
                    "bank",
                    models.TextField(
                        choices=[
                            ("KVB CA", "KVB CA"),
                            ("SBI CA", "SBI CA"),
                            ("SBI OD", "SBI OD"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.TextField(
                        choices=[
                            ("cheque", "Cheque"),
                            ("neft", "NEFT"),
                            ("upi", "UPI (IKEA)"),
                            ("cash_deposit", "Cash Deposit"),
                            ("self_transfer", "Self Transfer"),
                            ("others", "Others"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "cheque_status",
                    models.TextField(
                        blank=True,
                        choices=[("passed", "Passed"), ("bounced", "Bounced")],
                        db_default="passed",
                        default="passed",
                        null=True,
                    ),
                ),
                (
                    "cheque_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="bank_entry",
                        to="app.chequedeposit",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Bank",
                "unique_together": {("date", "idx", "bank")},
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "order_no",
                    models.TextField(max_length=60, primary_key=True, serialize=False),
                ),
                ("salesman", models.TextField(max_length=30)),
                ("date", models.DateField()),
                (
                    "type",
                    models.TextField(
                        blank=True,
                        choices=[("SH", "Shikhar"), ("SE", "Salesman")],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("place_order", models.BooleanField(db_default=False, default=False)),
                ("force_order", models.BooleanField(db_default=False, default=False)),
                ("creditlock", models.BooleanField(db_default=False, default=False)),
                ("release", models.BooleanField(db_default=False, default=False)),
                ("delete", models.BooleanField(db_default=False, default=False)),
                (
                    "beat",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="orders",
                        to="app.beat",
                    ),
                ),
                (
                    "billing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="app.billing",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="orders",
                        to="app.party",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orders",
                "verbose_name_plural": "Billing",
            },
        ),
        migrations.CreateModel(
            name="OrdersProxy",
            fields=[],
            options={
                "verbose_name": "order",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app.orders",),
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "inum",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("amt", models.FloatField(null=True)),
                ("ctin", models.CharField(blank=True, max_length=20, null=True)),
                ("gst_period", models.CharField(blank=True, max_length=12, null=True)),
                ("discount", models.FloatField(db_default=0, default=0)),
                ("roundoff", models.FloatField(db_default=0, default=0)),
                (
                    "type",
                    models.CharField(db_default="sales", max_length=15, null=True),
                ),
                ("tds", models.FloatField(db_default=0, default=0)),
                ("tcs", models.FloatField(db_default=0, default=0)),
                ("beat", models.TextField(max_length=40, null=True)),
                ("delivered", models.BooleanField(db_default=True, default=True)),
                (
                    "party",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.party",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sales",
            },
        ),
        migrations.CreateModel(
            name="Outstanding",
            fields=[
                (
                    "inum",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("balance", models.FloatField()),
                ("beat", models.TextField(max_length=40, null=True)),
                ("date", models.DateField()),
                (
                    "party",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.party",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Outstanding",
            },
        ),
        migrations.CreateModel(
            name="OpeningBalance",
            fields=[
                (
                    "inum",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("amt", models.FloatField(blank=True, null=True)),
                ("beat", models.TextField(max_length=40)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.party"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "inum",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("amt", models.FloatField(null=True)),
                ("mode", models.CharField(max_length=30)),
                (
                    "bank_entry",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="ikea_collection",
                        to="app.bankstatement",
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.sales",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.party",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Collection",
            },
        ),
        migrations.AddField(
            model_name="chequedeposit",
            name="party",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.party",
            ),
        ),
        migrations.CreateModel(
            name="PushedCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("party_code", models.TextField(max_length=30)),
                (
                    "billing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection",
                        to="app.billing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "bill",
                    models.OneToOneField(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="app.sales",
                    ),
                ),
                ("print_time", models.DateTimeField(blank=True, null=True)),
                (
                    "print_type",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("first_copy", "First Copy"),
                            ("loading_sheet", "Loading Sheet"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_reloaded", models.BooleanField(db_default=False, default=False)),
                ("reason", models.TextField(blank=True, max_length=100, null=True)),
                ("loading_time", models.DateTimeField(blank=True, null=True)),
                ("delivered_time", models.DateTimeField(blank=True, null=True)),
                ("irn", models.TextField(blank=True, null=True)),
                ("delivered", models.BooleanField(blank=True, null=True)),
                (
                    "delivery_reason",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("scanned", "Scanned"),
                            ("bill_with_shop", "Bill With Shop"),
                            ("cash_bill_success", "Cash Bill (Collected Money)"),
                            ("bill_return", "Bill Return"),
                            ("qrcode_not_found", "QR Code Not Found"),
                            ("others", "Other Reason"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "plain_loading_sheet",
                    models.BooleanField(db_default=False, default=False),
                ),
                ("cash_bill", models.BooleanField(db_default=False, default=False)),
                (
                    "loading_sheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="bills",
                        to="app.salesmanloadingsheet",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="bills",
                        to="app.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.TextField(max_length=100)),
                (
                    "batch",
                    models.TextField(
                        db_default="00000", default="00000", max_length=10
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("allocated", models.IntegerField()),
                ("rate", models.FloatField()),
                ("reason", models.TextField(max_length=50)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="app.orders",
                    ),
                ),
            ],
            options={
                "unique_together": {("order", "product", "batch")},
            },
        ),
        migrations.CreateModel(
            name="BankCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amt", models.IntegerField()),
                ("pushed", models.BooleanField(db_default=False, default=False)),
                (
                    "bank_entry",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection",
                        to="app.bankstatement",
                    ),
                ),
                (
                    "cheque_entry",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection",
                        to="app.chequedeposit",
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.outstanding",
                    ),
                ),
            ],
            options={
                "unique_together": {("bill", "cheque_entry", "bank_entry")},
            },
        ),
        migrations.CreateModel(
            name="Adjustment",
            fields=[
                (
                    "inum",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("amt", models.FloatField(null=True)),
                ("adj_amt", models.FloatField(default=0)),
                (
                    "from_bill",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="adjusted_from",
                        to="app.sales",
                    ),
                ),
                (
                    "to_bill",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="adjusted_to",
                        to="app.sales",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.party",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Adjustment",
                "unique_together": {("inum", "from_bill", "to_bill")},
            },
        ),
        migrations.CreateModel(
            name="PendingSheetBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("days", models.IntegerField()),
                ("outstanding_amt", models.IntegerField()),
                ("outstanding_on_ikea", models.IntegerField(null=True)),
                ("outstanding_on_bill", models.IntegerField(null=True)),
                ("outstanding_on_sheet", models.IntegerField(null=True)),
                (
                    "payment_mode",
                    models.TextField(
                        choices=[
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("neft", "NEFT"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "bill_status",
                    models.TextField(
                        choices=[
                            ("scanned", "Scanned"),
                            ("qrcode_not_found", "qrcode_not_found"),
                            ("loading_sheet", "loading_sheet"),
                            ("sales_return", "sales_return"),
                            ("bill_with_shop", "Bill With Shop"),
                            ("others", "Other Reason"),
                        ],
                        default="scanned",
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.sales",
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="app.pendingsheet",
                    ),
                ),
            ],
            options={
                "unique_together": {("sheet", "bill")},
            },
        ),
    ]
