# Generated by Django 5.1.1 on 2025-05-29 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_truckload_truckproduct_purchaseproduct"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseproduct",
            name="load",
        ),
        migrations.CreateModel(
            name="TruckPurchase",
            fields=[
                (
                    "inum",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                (
                    "load",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="purchase",
                        to="app.truckload",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="purchaseproduct",
            name="inum",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="app.truckpurchase",
            ),
        ),
    ]
