# Generated by Django 5.1.1 on 2025-05-29 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_purchaseproduct_load_truckpurchase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="truckproduct",
            name="load",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="truck_products",
                to="app.truckload",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="truckpurchase",
            name="load",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="purchases",
                to="app.truckload",
            ),
        ),
    ]
