# Generated by Django 5.1.1 on 2025-06-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_truckproduct_load_alter_truckpurchase_load"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="type",
            field=models.CharField(db_default="shop", max_length=10, null=True),
        ),
    ]
