# Generated by Django 5.1.1 on 2025-06-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_party_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankstatement",
            name="bank",
            field=models.TextField(
                choices=[
                    ("KVB CA", "KVB CA"),
                    ("SBI CA", "SBI CA"),
                    ("SBI OD", "SBI OD"),
                    ("SBI LAKME", "SBI LAKME"),
                ],
                max_length=20,
            ),
        ),
    ]
