# Generated by Django 5.1.1 on 2025-06-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_truckproduct_barcode_purchaseproduct_mrp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Barcode",
            fields=[
                (
                    "barcode",
                    models.CharField(max_length=300, primary_key=True, serialize=False),
                ),
                ("cbu", models.CharField(max_length=20)),
            ],
        ),
    ]
