# Generated by Django 5.1.1 on 2025-06-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_barcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="barcode",
            name="cbu",
        ),
        migrations.AddField(
            model_name="barcode",
            name="sku",
            field=models.CharField(
                default=None, max_length=20, primary_key=False, serialize=False
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="barcode",
            name="barcode",
            field=models.CharField(max_length=300),
        ),
    ]
