# Generated by Django 5.1.1 on 2025-06-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_remove_barcode_cbu_barcode_sku_alter_barcode_barcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barcode",
            name="sku",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
