# Generated by Django 5.1.1 on 2025-07-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_barcode_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="truckproduct",
            name="box",
            field=models.IntegerField(db_default=1, default=1),
        ),
    ]
