# Generated by Django 5.1.1 on 2025-07-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_truckproduct_box"),
    ]

    operations = [
        migrations.AddField(
            model_name="truckproduct",
            name="mrp",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
