# Generated by Django 5.1.1 on 2025-07-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_truckproduct_mrp"),
    ]

    operations = [
        migrations.CreateModel(
            name="BarcodeMap",
            fields=[
                (
                    "barcode",
                    models.CharField(max_length=300, primary_key=True, serialize=False),
                ),
                ("varient", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
