# Generated by Django 5.1.1 on 2025-08-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_barcodemap"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Barcode",
        ),
        migrations.AddField(
            model_name="barcodemap",
            name="sku",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
